server:
  port: 9000
  servlet:
    context-path: /

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
  profiles:
    active:
      - database
      - jwt
      - oauth2
      - cors
      - univcert
      - frontend

springdoc:
  swagger-ui:
    path: /
    csrf:
      enabled: true

logging:
  level:
    com.be.whereu: DEBUG
    org.springframework.web: INFO

